services:
  gateway:
    build: ./gateway
    image: gateway-img
    container_name: gateway
    ports:
      - "9001:9001"
    depends_on:
      - order
      - payment
    networks:
      - microservices-net

  order:
    build: ./order
    image: order-img
    container_name: order
    ports:
      - "8081:8081"
    networks:
      - microservices-net

  payment:
    build: ./payment
    image: payment-img
    container_name: payment
    ports:
      - "8082:8082"
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
